# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Staticwave
tagline:          'Moving yet staying in the same place'
description:      'The writings of Physicist turned Computational Neuroscientist about the academy, computers, and life'
url:              http://staticwave.ca
baseurl:          '/'
paginate:         5

author:
  name:           'Gabriel A. Devenyi'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gdevenyi/gdevenyi.github.io
